import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import Control from "@/app/Control";

export const metadata: Metadata = {
  title: "tutorials2",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const todos = await fetch("http://127.0.0.1:9999/todos", {cache:'no-cache'}).then((resp) => resp.json());
    const users = await fetch("http://127.0.0.1:9999/users", {cache:'no-cache'}).then((resp) => resp.json());

  return (
    <html>
      <body>
        <h2>
          <Link href="/">nextjs</Link>
        </h2>
        <div>
          <p>todos</p>
          <ul>
            {todos.map((m:any) => (
              <li>
                <Link href={`/todos/${m.id}`}>{m.content}</Link>
              </li>
            ))}
          </ul>
          <p>users</p>
          <ul>
              {users.map((m:any) => (
                  <li>
                      <Link href={`/users/${m.id}`}>{m.name}</Link>
                  </li>
              ))}
          </ul>
        </div>

        {children}


        <Control/>
      </body>
    </html>
  );
}
